import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  root: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  scrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.64)',
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    paddingTop: 24,
    overflow: 'hidden',
  },
  content: {
    paddingHorizontal: 37,
    gap: 21,
    paddingBottom: 36,
  },
  title: {
    fontFamily: 'DMSans-SemiBold',
    fontSize: 18,
    lineHeight: 24,
    color: '#1D1617',
  },
  description: {
    fontFamily: 'DMSans-Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#7B6F72',
  },
  steps: {
    marginTop: 4,
  },
  stepRow: {
    flexDirection: 'row',
    gap: 14,
  },
  stepNumber: {
    width: 18,
    fontFamily: 'DMSans-Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#2ABFA0',
    marginRight: 7,
  },
  stepMarkerColumn: {
    width: 20,
    alignItems: 'center',
  },
  stepDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#2ABFA0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2ABFA0',
  },
  stepLine: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  stepLineDot: {
    width: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#2ABFA0',
  },
  stepText: {
    flex: 1,
    fontFamily: 'DMSans-Bold',
    fontSize: 14,
    lineHeight: 21,
    color: '#1D1617',
    paddingBottom: 24,
  },
  holdBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#D6455D',
    paddingVertical: 19,
    paddingHorizontal: 40,
  },
  holdCount: {
    fontFamily: 'DMSans-Bold',
    fontSize: 18,
    color: '#FFFFFF',
  },
  holdLabel: {
    fontFamily: 'DMSans-Bold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  statusBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#D6455D',
    paddingVertical: 19,
    paddingHorizontal: 24,
  },
  cancelButton: {
    marginLeft: 'auto',
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  cancelButtonText: {
    fontFamily: 'DMSans-Bold',
    fontSize: 13,
    color: '#FFFFFF',
  },
  resultContent: {
    paddingHorizontal: 37,
    paddingTop: 8,
    paddingBottom: 36,
    alignItems: 'center',
    gap: 14,
  },
  resultIcon: {
    marginBottom: 4,
  },
  resultButtonRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  primaryButton: {
    backgroundColor: '#D6455D',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  primaryButtonText: {
    fontFamily: 'DMSans-Bold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  secondaryButton: {
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D6455D',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  secondaryButtonText: {
    fontFamily: 'DMSans-Bold',
    fontSize: 14,
    color: '#D6455D',
  },
});

export default styles;
