import {StyleSheet} from 'react-native';
import {layout} from '~/theme/tokens';

const styles = StyleSheet.create({
  sheet: {
    paddingTop: 4,
    minHeight: '82%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: layout.screenGutter,
    paddingBottom: 4,
  },
  headerSpacer: {
    width: 22,
    height: 22,
  },
  closeButton: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    paddingHorizontal: layout.screenGutter,
    gap: 18,
    paddingBottom: 28,
  },
  title: {
    fontFamily: 'DMSans-SemiBold',
    fontSize: 18,
    lineHeight: 24,
    color: '#1D1617',
  },
  description: {
    fontFamily: 'DMSans-Regular',
    fontSize: 15,
    lineHeight: 22,
    color: '#7B6F72',
  },
  resultDescription: {
    fontFamily: 'DMSans-Regular',
    fontSize: 15,
    lineHeight: 22,
    color: '#7B6F72',
    textAlign: 'center',
    maxWidth: 320,
  },
  locationCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#D9E4F0',
    backgroundColor: '#F7FAFD',
    padding: 14,
    gap: 12,
  },
  locationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  locationHeaderCopy: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  locationTitleColumn: {
    flex: 1,
    gap: 2,
  },
  locationTitle: {
    fontFamily: 'DMSans-Bold',
    fontSize: 14,
    lineHeight: 18,
    color: '#1D1617',
  },
  locationSubtitle: {
    fontFamily: 'DMSans-Regular',
    fontSize: 13,
    lineHeight: 18,
    color: '#7B6F72',
  },
  mapPreview: {
    width: '100%',
    height: 132,
    borderRadius: 14,
    backgroundColor: '#E8EEF5',
  },
  mapPreviewPlaceholder: {
    height: 132,
    borderRadius: 14,
    backgroundColor: '#E8EEF5',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  mapPreviewPlaceholderText: {
    fontFamily: 'DMSans-Regular',
    fontSize: 13,
    lineHeight: 18,
    color: '#7B6F72',
    textAlign: 'center',
  },
  locationMeta: {
    fontFamily: 'DMSans-Medium',
    fontSize: 12,
    lineHeight: 16,
    color: '#50657D',
  },
  steps: {
    marginTop: 4,
    marginBottom: 4,
  },
  stepRow: {
    flexDirection: 'row',
    gap: 14,
  },
  stepNumber: {
    width: 18,
    fontFamily: 'DMSans-Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#2ABFA0',
    marginRight: 7,
  },
  stepMarkerColumn: {
    width: 20,
    alignItems: 'center',
  },
  stepDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#2ABFA0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2ABFA0',
  },
  stepLine: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  stepLineDot: {
    width: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#2ABFA0',
  },
  stepText: {
    flex: 1,
    fontFamily: 'DMSans-Bold',
    fontSize: 14,
    lineHeight: 21,
    color: '#1D1617',
    paddingBottom: 24,
  },
  actionArea: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 2,
    paddingBottom: 2,
  },
  holdButtonContainer: {
    width: '86%',
    maxWidth: 340,
    minHeight: 76,
    borderRadius: 18,
    shadowColor: '#D6455D',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 5,
  },
  holdPressableButton: {
    borderRadius: 18,
  },
  holdButton: {
    minHeight: 76,
    borderRadius: 18,
    backgroundColor: '#D6455D',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 22,
  },
  holdProgressFill: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    height: 5,
    backgroundColor: '#B51632',
  },
  holdButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  holdCount: {
    fontFamily: 'DMSans-Bold',
    fontSize: 34,
    lineHeight: 38,
    color: '#FFFFFF',
    textAlign: 'center',
    minWidth: 36,
  },
  holdSecondsLabel: {
    fontFamily: 'DMSans-Medium',
    fontSize: 11,
    lineHeight: 14,
    color: 'rgba(255, 255, 255, 0.78)',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginTop: 2,
  },
  holdLabel: {
    fontFamily: 'DMSans-Bold',
    fontSize: 14,
    lineHeight: 18,
    color: '#FFFFFF',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  sendingButton: {
    backgroundColor: '#B51632',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  resultContent: {
    paddingHorizontal: layout.screenGutter,
    paddingTop: 8,
    paddingBottom: 36,
    alignItems: 'center',
    gap: 14,
  },
  resultIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF0F2',
    marginBottom: 4,
  },
  resultDetailsBox: {
    width: '100%',
    borderRadius: 18,
    backgroundColor: '#FFF0F2',
    borderWidth: 1,
    borderColor: '#F5C3CC',
    padding: 16,
    gap: 6,
  },
  resultDetailsTitle: {
    fontFamily: 'DMSans-Bold',
    fontSize: 15,
    lineHeight: 20,
    color: '#B51632',
  },
  resultDetails: {
    fontFamily: 'DMSans-Regular',
    fontSize: 14,
    lineHeight: 20,
    color: '#1D1617',
  },
  resultButtonRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  primaryButton: {
    backgroundColor: '#D6455D',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  primaryButtonText: {
    fontFamily: 'DMSans-Bold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  secondaryButton: {
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D6455D',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  secondaryButtonText: {
    fontFamily: 'DMSans-Bold',
    fontSize: 14,
    color: '#D6455D',
  },
});

export default styles;
