export enum AsyncStorageEnum {
  RetryGeoPosition = '@retryGeoPosition',
  GoogleFitAuthorized = '@googleFitAuthorized',
  HasSeenOnboarding = '@hasSeenOnboarding',
  LastSavedPushToken = '@lastSavedPushToken',
  PersistedAutomatedEmergencySettings = 'persist:automatedEmergency',
  PersistedHealthLogs = 'persist:health',
  PersistedUserSettings = 'persist:user',
  LoggerData = '@loggerData',
  IsEmergencyEscalationStarted = '@isEmergencyEscalationStarted',
  HealthTrigger = '@HealthTrigger',
  TimeTrigger = '@TimeTrigger',
  BioData = '@BioData',
  StartingDate = '@StartingDate',
  LastUpdatedDate = '@LastUpdatedDate',
  LongestPeriod = '@LongestPeriod',
  RecommendedPeriod = '@RecommendedPeriod',
  Language = '@language',
  SleepSchedule = '@SleepSchedule',
  SmartDetectionSettings = '@SmartDetectionSettings',
  TimezoneBaseline = '@TimezoneBaseline',
  TravelDetectedAt = '@TravelDetectedAt',
  ConsecutiveNoDataCount = '@ConsecutiveNoDataCount',
  ManualEmergencyInProgress = '@ManualEmergencyInProgress',
}
